\set ON_ERROR_STOP on

-- Minimal synthetic reconstruction of the import objects required by
-- 20261001064839_import_authorization_containment.sql. No production data or
-- identifiers are present. The legacy commit bodies are deliberately tiny;
-- the migration under test moves them unchanged and wraps their public API.

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin bypassrls;
  end if;
end
$$;

create schema auth;
create schema private;
grant usage on schema public, auth to anon, authenticated, service_role;

create function auth.uid()
returns uuid
language sql
stable
as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;

create table auth.users (
  id uuid primary key,
  aud text,
  role text,
  email text,
  email_confirmed_at timestamptz,
  raw_app_meta_data jsonb,
  raw_user_meta_data jsonb,
  created_at timestamptz,
  updated_at timestamptz
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'user' check (role in ('admin', 'user')),
  is_active boolean not null default true
);

create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email);
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create function private.current_user_is_active_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and is_active is true
  );
$$;

create function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and is_active is true
  );
$$;

create function public.is_admin()
returns boolean
language sql
stable
as $$
  select coalesce(
    (current_setting('request.jwt.claims', true)::jsonb #>> '{app_metadata,role}') = 'admin',
    false
  );
$$;

create function public.nullif_blank(value text)
returns text
language sql
immutable
as $$ select nullif(btrim(value), '') $$;

create function public.try_cast_double(value text)
returns double precision
language plpgsql
stable
as $$
begin
  return public.nullif_blank(value)::double precision;
exception when others then
  return null;
end;
$$;

create table public.stg_biopsies (
  id bigint generated by default as identity primary key,
  import_batch_id uuid not null,
  source_file text not null,
  row_no integer not null,
  raw jsonb not null
);
create table public.stg_drone_photos (
  id bigint generated by default as identity primary key,
  import_batch_id uuid not null,
  source_file text not null,
  row_no integer not null,
  raw jsonb not null
);
create table public.stg_import_errors (
  import_batch_id uuid,
  source_file text,
  row_no integer,
  raw jsonb
);
create table public.catalog (
  pk_catalog_id integer generated by default as identity primary key,
  name text
);
create table public.sightings (
  pk_sighting_id integer generated by default as identity primary key,
  sighting_date date,
  start_time text,
  end_time text,
  photographer text,
  island text,
  sitelocation text,
  latitude numeric,
  longitude numeric,
  notes text,
  total_mantas_biopsied integer
);
create table public.mantas (
  pk_manta_id integer generated by default as identity primary key,
  fk_sighting_id integer references public.sightings(pk_sighting_id) on delete cascade,
  fk_catalog_id integer references public.catalog(pk_catalog_id)
);
create table public.photos (
  pk_photo_id integer generated by default as identity primary key,
  fk_manta_id integer references public.mantas(pk_manta_id),
  fk_sighting_id integer references public.sightings(pk_sighting_id),
  fk_catalog_id integer references public.catalog(pk_catalog_id),
  storage_path text,
  file_name2 text,
  photo_view text,
  is_best_manta_ventral_photo boolean
);
create table public.sighting_submissions (
  id uuid primary key default gen_random_uuid(),
  submitted_at timestamptz not null default now(),
  email text not null,
  sighting_date date,
  manta_count integer not null default 0,
  photo_count integer not null default 0,
  payload jsonb,
  status text not null default 'pending',
  committed_at timestamptz,
  committed_pk_sighting_id integer
);
create table public.biopsies (
  pk_biopsy_id bigint generated by default as identity primary key,
  fk_manta_id integer references public.mantas(pk_manta_id),
  fk_sighting_id integer references public.sightings(pk_sighting_id),
  fk_catalog_id integer references public.catalog(pk_catalog_id),
  sample_date date,
  sample_time time without time zone,
  collector text,
  method text,
  island text,
  region text,
  location text,
  tissue_type text,
  lab_id text,
  notes text,
  source text,
  raw_sample_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create table public.drone_photos (id bigint generated by default as identity);

create function public.commit_sighting_submission(sub_id uuid)
returns void
language plpgsql
as $$
declare
  submission_row public.sighting_submissions%rowtype;
  manta jsonb;
  photo jsonb;
  new_sighting_id integer;
  new_manta_id integer;
  resolved_catalog_id integer;
  resolved_sitelocation text;
  resolved_storage_path text;
  resolved_file_name text;
begin
  select *
  into submission_row
  from public.sighting_submissions
  where id = sub_id
  for update;
  if not found then raise exception 'Submission not found'; end if;
  if submission_row.status = 'committed' and submission_row.committed_pk_sighting_id is not null then return; end if;
  resolved_sitelocation := nullif(trim(coalesce(submission_row.payload->>'sitelocation', submission_row.payload->>'locationName')), '');
  insert into public.sightings (sighting_date, start_time, end_time, photographer, island, sitelocation, latitude, longitude, notes)
  values (coalesce(submission_row.sighting_date, nullif(submission_row.payload->>'date', '')::date), nullif(submission_row.payload->>'startTime', ''), nullif(submission_row.payload->>'stopTime', ''), nullif(submission_row.payload->>'photographer', ''), nullif(submission_row.payload->>'island', ''), resolved_sitelocation, nullif(submission_row.payload->>'latitude', '')::numeric, nullif(submission_row.payload->>'longitude', '')::numeric, nullif(submission_row.payload->>'notes', ''))
  returning pk_sighting_id into new_sighting_id;
  for manta in select value from jsonb_array_elements(coalesce(submission_row.payload->'mantas', '[]'::jsonb)) loop
    resolved_catalog_id := coalesce(nullif(manta->>'matchedCatalogId', '')::integer, nullif(manta->>'potentialCatalogId', '')::integer, nullif(manta->>'suggested_catalog_id', '')::integer);
    if coalesce((manta->>'noMatch')::boolean, false) is true then
      insert into public.catalog (name) values (coalesce(nullif(manta->>'name', ''), 'Pending Name')) returning pk_catalog_id into resolved_catalog_id;
    elsif resolved_catalog_id is null then
      raise exception 'Cannot commit submission';
    end if;
    insert into public.mantas (
      fk_sighting_id,
      fk_catalog_id
    )
    values (
      new_sighting_id,
      resolved_catalog_id
    )
    returning pk_manta_id into new_manta_id;
    for photo in select value from jsonb_array_elements(coalesce(manta->'photos', '[]'::jsonb)) loop
      resolved_storage_path := nullif(coalesce(photo->>'path', photo->>'url'), '');
      resolved_file_name := coalesce(nullif(photo->>'name', ''), nullif(photo->>'id', ''), 'uploaded-photo');
      insert into public.photos (fk_manta_id, fk_sighting_id, fk_catalog_id, storage_path, file_name2, photo_view, is_best_manta_ventral_photo)
      values (new_manta_id, new_sighting_id, resolved_catalog_id, resolved_storage_path, resolved_file_name, coalesce(nullif(photo->>'view', ''), 'ventral'), coalesce((photo->>'isBestVentral')::boolean, false));
    end loop;
  end loop;
  update public.sighting_submissions set status = 'committed', committed_at = now(), committed_pk_sighting_id = new_sighting_id where id = sub_id;
end;
$$;

alter table public.stg_biopsies enable row level security;
alter table public.stg_drone_photos enable row level security;
create policy stg_biopsies_admin_ins on public.stg_biopsies
for insert to authenticated with check (public.is_admin());
create policy stg_biopsies_admin_sel on public.stg_biopsies
for select to authenticated using (public.is_admin());
create policy stg_drone_photos_admin_ins on public.stg_drone_photos
for insert to authenticated with check (public.is_admin());
create policy stg_drone_photos_admin_sel on public.stg_drone_photos
for select to authenticated using (public.is_admin());

create view public.v_stg_biopsies_norm as
select id, import_batch_id, source_file, row_no, raw,
       public.try_cast_double(raw->>'latitude') as latitude,
       public.try_cast_double(raw->>'longitude') as longitude
from public.stg_biopsies;
create view public.v_stg_drone_photos_norm as
select id, import_batch_id, source_file, row_no, raw,
       public.try_cast_double(raw->>'drone_lat') as drone_lat,
       public.try_cast_double(raw->>'drone_lon') as drone_lon
from public.stg_drone_photos;
create view public.v_stg_invalid_biopsies as
select * from public.v_stg_biopsies_norm where false;
create view public.v_stg_invalid_drone_photos as
select * from public.v_stg_drone_photos_norm where false;

create function public.fn_imports_commit_biopsies(p_batch uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform 1 from public.v_stg_biopsies_norm where import_batch_id = p_batch;
  if false then
    insert into public.stg_import_errors values (p_batch, null, null, null);
    insert into public.biopsies default values;
  end if;
  return jsonb_build_object(
    'batch', p_batch, 'target', 'biopsies', 'inserted', 0, 'updated', 0,
    'invalid', 0, 'skipped', 0, 'errors_table', 'stg_import_errors',
    'invalid_view', 'v_stg_invalid_biopsies'
  );
end;
$$;

create function public.fn_imports_commit_drone_photos(p_batch uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform 1 from public.v_stg_drone_photos_norm where import_batch_id = p_batch;
  if false then
    insert into public.stg_import_errors values (p_batch, null, null, null);
    insert into public.drone_photos default values;
  end if;
  return jsonb_build_object(
    'batch', p_batch, 'target', 'drone_photos', 'inserted', 0, 'updated', 0,
    'invalid', 0, 'skipped', 0, 'errors_table', 'stg_import_errors',
    'invalid_view', 'v_stg_invalid_drone_photos'
  );
end;
$$;

grant execute on function public.is_admin(), public.is_admin_user() to anon, authenticated, service_role;
grant execute on function public.fn_imports_commit_biopsies(uuid) to public, anon, authenticated, service_role;
grant execute on function public.fn_imports_commit_drone_photos(uuid) to public, anon, authenticated, service_role;
grant all privileges on table public.stg_biopsies, public.stg_drone_photos to anon, authenticated, service_role;
grant all privileges on sequence public.stg_biopsies_id_seq, public.stg_drone_photos_id_seq to anon, authenticated, service_role;
grant all privileges on table public.v_stg_biopsies_norm, public.v_stg_drone_photos_norm to anon, authenticated, service_role;
grant all privileges on table public.v_stg_invalid_biopsies, public.v_stg_invalid_drone_photos to anon, authenticated, service_role;
grant all privileges on table public.catalog, public.sightings, public.mantas, public.photos,
  public.sighting_submissions, public.biopsies to anon, authenticated, service_role;
grant all privileges on all sequences in schema public to anon, authenticated, service_role;
grant execute on function public.commit_sighting_submission(uuid) to anon, authenticated, service_role;

-- Fabricated sentinels prove both forward migration and rollback preserve data.
insert into public.catalog (pk_catalog_id, name) values (-1, 'Synthetic existing catalog');
insert into public.sightings (pk_sighting_id, sighting_date, island, sitelocation)
values (-1, date '2020-01-01', 'Synthetic Island', 'Synthetic Existing Site');
insert into public.mantas (pk_manta_id, fk_sighting_id, fk_catalog_id)
values (-1, -1, -1);
insert into public.photos (
  pk_photo_id, fk_manta_id, fk_sighting_id, fk_catalog_id,
  storage_path, file_name2, photo_view
) values (
  -1, -1, -1, -1, 'synthetic/existing.jpg', 'existing.jpg', 'ventral'
);
insert into public.biopsies (
  pk_biopsy_id, fk_manta_id, fk_sighting_id, fk_catalog_id,
  sample_date, collector, method, tissue_type, source, raw_sample_id
) values (
  -1, -1, -1, -1, date '2020-01-01', 'Synthetic Existing Collector',
  'synthetic method', 'synthetic tissue', 'synthetic_existing', 'SYNTHETIC-EXISTING'
);
insert into public.stg_biopsies (import_batch_id, source_file, row_no, raw)
values ('10000000-0000-4000-8000-000000000099', 'synthetic-existing.csv', 1, '{}'::jsonb);
