\set ON_ERROR_STOP on

-- Minimal synthetic reconstruction of the import objects required by
-- 20261001064839_import_authorization_containment.sql. No production data or
-- identifiers are present. The legacy commit bodies are deliberately tiny;
-- the migration under test moves them unchanged and wraps their public API.

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin bypassrls;
  end if;
end
$$;

create schema auth;
create schema private;
grant usage on schema public, auth to anon, authenticated, service_role;

create function auth.uid()
returns uuid
language sql
stable
as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;

create table auth.users (
  id uuid primary key,
  aud text,
  role text,
  email text,
  email_confirmed_at timestamptz,
  raw_app_meta_data jsonb,
  raw_user_meta_data jsonb,
  created_at timestamptz,
  updated_at timestamptz
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'user' check (role in ('admin', 'user')),
  is_active boolean not null default true
);

create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email);
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create function private.current_user_is_active_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and is_active is true
  );
$$;

create function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and is_active is true
  );
$$;

create function public.is_admin()
returns boolean
language sql
stable
as $$
  select coalesce(
    (current_setting('request.jwt.claims', true)::jsonb #>> '{app_metadata,role}') = 'admin',
    false
  );
$$;

create function public.nullif_blank(value text)
returns text
language sql
immutable
as $$ select nullif(btrim(value), '') $$;

create function public.try_cast_double(value text)
returns double precision
language plpgsql
stable
as $$
begin
  return public.nullif_blank(value)::double precision;
exception when others then
  return null;
end;
$$;

create table public.stg_biopsies (
  id bigint generated by default as identity primary key,
  import_batch_id uuid not null,
  source_file text not null,
  row_no integer not null,
  raw jsonb not null
);
create table public.stg_drone_photos (
  id bigint generated by default as identity primary key,
  import_batch_id uuid not null,
  source_file text not null,
  row_no integer not null,
  raw jsonb not null
);
create table public.stg_import_errors (
  import_batch_id uuid,
  source_file text,
  row_no integer,
  raw jsonb
);
create table public.biopsies (id bigint generated by default as identity);
create table public.drone_photos (id bigint generated by default as identity);

alter table public.stg_biopsies enable row level security;
alter table public.stg_drone_photos enable row level security;
create policy stg_biopsies_admin_ins on public.stg_biopsies
for insert to authenticated with check (public.is_admin());
create policy stg_biopsies_admin_sel on public.stg_biopsies
for select to authenticated using (public.is_admin());
create policy stg_drone_photos_admin_ins on public.stg_drone_photos
for insert to authenticated with check (public.is_admin());
create policy stg_drone_photos_admin_sel on public.stg_drone_photos
for select to authenticated using (public.is_admin());

create view public.v_stg_biopsies_norm as
select id, import_batch_id, source_file, row_no, raw,
       public.try_cast_double(raw->>'latitude') as latitude,
       public.try_cast_double(raw->>'longitude') as longitude
from public.stg_biopsies;
create view public.v_stg_drone_photos_norm as
select id, import_batch_id, source_file, row_no, raw,
       public.try_cast_double(raw->>'drone_lat') as drone_lat,
       public.try_cast_double(raw->>'drone_lon') as drone_lon
from public.stg_drone_photos;
create view public.v_stg_invalid_biopsies as
select * from public.v_stg_biopsies_norm where false;
create view public.v_stg_invalid_drone_photos as
select * from public.v_stg_drone_photos_norm where false;

create function public.fn_imports_commit_biopsies(p_batch uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform 1 from public.v_stg_biopsies_norm where import_batch_id = p_batch;
  if false then
    insert into public.stg_import_errors values (p_batch, null, null, null);
    insert into public.biopsies default values;
  end if;
  return jsonb_build_object(
    'batch', p_batch, 'target', 'biopsies', 'inserted', 0, 'updated', 0,
    'invalid', 0, 'skipped', 0, 'errors_table', 'stg_import_errors',
    'invalid_view', 'v_stg_invalid_biopsies'
  );
end;
$$;

create function public.fn_imports_commit_drone_photos(p_batch uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform 1 from public.v_stg_drone_photos_norm where import_batch_id = p_batch;
  if false then
    insert into public.stg_import_errors values (p_batch, null, null, null);
    insert into public.drone_photos default values;
  end if;
  return jsonb_build_object(
    'batch', p_batch, 'target', 'drone_photos', 'inserted', 0, 'updated', 0,
    'invalid', 0, 'skipped', 0, 'errors_table', 'stg_import_errors',
    'invalid_view', 'v_stg_invalid_drone_photos'
  );
end;
$$;

grant execute on function public.is_admin(), public.is_admin_user() to anon, authenticated, service_role;
grant execute on function public.fn_imports_commit_biopsies(uuid) to public, anon, authenticated, service_role;
grant execute on function public.fn_imports_commit_drone_photos(uuid) to public, anon, authenticated, service_role;
grant all privileges on table public.stg_biopsies, public.stg_drone_photos to anon, authenticated, service_role;
grant all privileges on sequence public.stg_biopsies_id_seq, public.stg_drone_photos_id_seq to anon, authenticated, service_role;
grant all privileges on table public.v_stg_biopsies_norm, public.v_stg_drone_photos_norm to anon, authenticated, service_role;
grant all privileges on table public.v_stg_invalid_biopsies, public.v_stg_invalid_drone_photos to anon, authenticated, service_role;
