[functions]
[functions.admin-user-management]
enabled = true
verify_jwt = true

[functions.admin-create-user]
enabled = true
verify_jwt = true

[functions.admin-set-password]
enabled = true
verify_jwt = true

[functions.list-users]
enabled = true
verify_jwt = true

[functions.create-user]
enabled = true
verify_jwt = true

[functions.delete-manta]
enabled = true
verify_jwt = true

[functions.delete-photo]
enabled = true
verify_jwt = true

[functions.commit-drone-draft]
enabled = true
verify_jwt = true

[functions.generate-newphoto-embedding]
enabled = true
verify_jwt = true

[functions.catalog_selfmatch]
enabled = true
verify_jwt = true

[functions.merge-catalogs]
enabled = true
verify_jwt = true

[functions.bootstrap-admin]
enabled = false

[functions.confirm-user]
enabled = false

[functions.db_check]
enabled = false

[functions.embeddings-catalog-missing]
enabled = false

[functions.match-manta]
enabled = false

[functions.stream-sighting-embedding-update]
enabled = false

[functions.test-embed-fix]
enabled = false

[functions.update-password]
enabled = false

[functions.whoami]
enabled = false

[functions.envtest]
enabled = false

[functions.jwt-debug]
enabled = false

[functions.embeddings-sighting]
verify_jwt = false

[functions.embeddings-catalog]
verify_jwt = false

[functions.embeddings-photo]
verify_jwt = false
