[functions]
[functions.admin-user-management]
enabled = true
verify_jwt = true

[functions.admin-create-user]
enabled = true
verify_jwt = true

[functions.admin-set-password]
enabled = true
verify_jwt = true

[functions.list-users]
enabled = true
verify_jwt = true

[functions.embeddings-sighting]
verify_jwt = false

[functions.embeddings-catalog]
verify_jwt = false

[functions.embeddings-photo]
verify_jwt = false