[functions]
[functions.admin-user-management]
enabled = true
verify_jwt = true

[functions.admin-create-user]
enabled = true
verify_jwt = true

[functions.admin-set-password]
enabled = true
verify_jwt = true

[functions.list-users]
enabled = true
verify_jwt = true

[functions.create-user]
enabled = true
verify_jwt = true

[functions.delete-manta]
enabled = true
verify_jwt = true

[functions.delete-photo]
enabled = true
verify_jwt = true

[functions.commit-drone-draft]
enabled = true
verify_jwt = true

[functions.generate-newphoto-embedding]
enabled = true
verify_jwt = true

[functions.embeddings-sighting]
verify_jwt = false

[functions.embeddings-catalog]
verify_jwt = false

[functions.embeddings-photo]
verify_jwt = false
